"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 06:25:35.052826
"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2  # noqa: F401
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('districts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('name', name=op.f('uq_districts_name'))
    )
    op.create_geospatial_index('idx_districts_geom', 'districts', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('talukas',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_talukas_district_id_districts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talukas'))
    )
    op.create_geospatial_index('idx_talukas_geom', 'talukas', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_talukas_district_id'), 'talukas', ['district_id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('state_admin', 'district_officer', 'drone_operator', 'field_verifier', name='user_role'), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_users_district_id_districts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_geospatial_table('villages',
    sa.Column('taluka_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taluka_id'], ['talukas.id'], name=op.f('fk_villages_taluka_id_talukas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_villages'))
    )
    op.create_geospatial_index('idx_villages_geom', 'villages', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_villages_taluka_id'), 'villages', ['taluka_id'], unique=False)
    op.create_geospatial_table('surveys',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('crop_survey', 'crop_health', 'damage_assessment', 'insurance_verification', 'subsidy_verification', name='survey_type'), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('taluka_id', sa.Uuid(), nullable=True),
    sa.Column('village_id', sa.Uuid(), nullable=True),
    sa.Column('aoi', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('aoi_area_ha', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'planned', 'flying', 'uploaded', 'processing', 'processed', 'verified', 'archived', name='survey_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('season', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_surveys_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_surveys_district_id_districts')),
    sa.ForeignKeyConstraint(['taluka_id'], ['talukas.id'], name=op.f('fk_surveys_taluka_id_talukas')),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('fk_surveys_village_id_villages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys'))
    )
    op.create_geospatial_index('idx_surveys_aoi', 'surveys', ['aoi'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_surveys_created_by'), 'surveys', ['created_by'], unique=False)
    op.create_index(op.f('ix_surveys_district_id'), 'surveys', ['district_id'], unique=False)
    op.create_index(op.f('ix_surveys_status'), 'surveys', ['status'], unique=False)
    op.create_index(op.f('ix_surveys_taluka_id'), 'surveys', ['taluka_id'], unique=False)
    op.create_index(op.f('ix_surveys_village_id'), 'surveys', ['village_id'], unique=False)
    op.create_table('missions',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('camera_profile', sa.String(length=64), nullable=False),
    sa.Column('aircraft_profile', sa.String(length=64), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('front_overlap', sa.Float(), nullable=False),
    sa.Column('side_overlap', sa.Float(), nullable=False),
    sa.Column('speed_ms', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('gsd_cm', sa.Float(), nullable=True),
    sa.Column('est_images', sa.Integer(), nullable=True),
    sa.Column('est_flights', sa.Integer(), nullable=True),
    sa.Column('est_area_ha', sa.Float(), nullable=True),
    sa.Column('flights_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waypoint_files_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'authorized', 'in_flight', 'completed', 'cancelled', name='mission_status'), nullable=False),
    sa.Column('authorized_by', sa.Uuid(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.id'], name=op.f('fk_missions_authorized_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_missions_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions'))
    )
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_index(op.f('ix_missions_survey_id'), 'missions', ['survey_id'], unique=False)
    op.create_geospatial_table('plots',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('plot_code', sa.String(length=64), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('village_id', sa.Uuid(), nullable=True),
    sa.Column('parcel_ref', sa.String(length=120), nullable=True),
    sa.Column('is_candidate', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_plots_survey_id_surveys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('fk_plots_village_id_villages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plots')),
    sa.UniqueConstraint('survey_id', 'plot_code', name='uq_plots_survey_code')
    )
    op.create_geospatial_index('idx_plots_geom', 'plots', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_plots_survey_id'), 'plots', ['survey_id'], unique=False)
    op.create_index(op.f('ix_plots_village_id'), 'plots', ['village_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('validate', 'geotag', 'calibrate', 'photogrammetry', 'indices', 'plots', 'classify', 'damage', 'report', name='job_kind'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_processing_jobs_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_survey_id'), 'processing_jobs', ['survey_id'], unique=False)
    op.create_geospatial_table('rasters',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('orthomosaic', 'dsm', 'dtm', 'ndvi', 'gndvi', 'ndre', 'stress', 'damage', name='raster_kind'), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('cog_url', sa.String(length=1024), nullable=True),
    sa.Column('crs', sa.String(length=64), nullable=True),
    sa.Column('gsd_cm', sa.Float(), nullable=True),
    sa.Column('bounds', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('calibrated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_rasters_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rasters'))
    )
    op.create_geospatial_index('idx_rasters_bounds', 'rasters', ['bounds'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_rasters_survey_id'), 'rasters', ['survey_id'], unique=False)
    op.create_table('reports',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('object_key_pdf', sa.String(length=512), nullable=True),
    sa.Column('object_key_csv', sa.String(length=512), nullable=True),
    sa.Column('object_key_geojson', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_reports_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_survey_id'), 'reports', ['survey_id'], unique=False)
    op.create_table('alerts',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=True),
    sa.Column('plot_id', sa.Uuid(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], name=op.f('fk_alerts_plot_id_plots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_alerts_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_plot_id'), 'alerts', ['plot_id'], unique=False)
    op.create_index(op.f('ix_alerts_survey_id'), 'alerts', ['survey_id'], unique=False)
    op.create_table('damage_assessments',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('before_survey_id', sa.Uuid(), nullable=False),
    sa.Column('after_survey_id', sa.Uuid(), nullable=False),
    sa.Column('ndvi_before', sa.Float(), nullable=True),
    sa.Column('ndvi_after', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('class', sa.Enum('none', 'low', 'moderate', 'severe', name='damage_class'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['after_survey_id'], ['surveys.id'], name=op.f('fk_damage_assessments_after_survey_id_surveys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['before_survey_id'], ['surveys.id'], name=op.f('fk_damage_assessments_before_survey_id_surveys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], name=op.f('fk_damage_assessments_plot_id_plots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_damage_assessments'))
    )
    op.create_index(op.f('ix_damage_assessments_plot_id'), 'damage_assessments', ['plot_id'], unique=False)
    op.create_table('flights',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('flight_no', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('area_covered_ha', sa.Float(), nullable=True),
    sa.Column('images_captured', sa.Integer(), nullable=True),
    sa.Column('rtk_fix_pct', sa.Float(), nullable=True),
    sa.Column('log_object_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_flights_mission_id_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flights'))
    )
    op.create_index(op.f('ix_flights_mission_id'), 'flights', ['mission_id'], unique=False)
    op.create_table('plot_ai_results',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('crop_pred', sa.String(length=64), nullable=True),
    sa.Column('crop_confidence', sa.Float(), nullable=True),
    sa.Column('ndvi_mean', sa.Float(), nullable=True),
    sa.Column('ndvi_p10', sa.Float(), nullable=True),
    sa.Column('ndvi_p90', sa.Float(), nullable=True),
    sa.Column('health_class', sa.Enum('healthy', 'moderate', 'severe', name='health_class'), nullable=True),
    sa.Column('stress_pct', sa.Float(), nullable=True),
    sa.Column('damage_pct', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], name=op.f('fk_plot_ai_results_plot_id_plots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_plot_ai_results_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot_ai_results'))
    )
    op.create_index(op.f('ix_plot_ai_results_plot_id'), 'plot_ai_results', ['plot_id'], unique=False)
    op.create_index(op.f('ix_plot_ai_results_survey_id'), 'plot_ai_results', ['survey_id'], unique=False)
    op.create_table('plot_verifications',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=True),
    sa.Column('actual_crop', sa.String(length=64), nullable=True),
    sa.Column('crop_stage', sa.String(length=64), nullable=True),
    sa.Column('health_class', postgresql.ENUM('healthy', 'moderate', 'severe', name='health_class', create_type=False), nullable=True),
    sa.Column('damage_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_keys', postgresql.ARRAY(sa.String(length=512)), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Enum('verified', 'needs_review', 'rejected', name='verification_decision'), nullable=True),
    sa.Column('client_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], name=op.f('fk_plot_verifications_plot_id_plots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_plot_verifications_survey_id_surveys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_plot_verifications_verifier_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot_verifications')),
    sa.UniqueConstraint('client_uuid', name=op.f('uq_plot_verifications_client_uuid'))
    )
    op.create_index(op.f('ix_plot_verifications_plot_id'), 'plot_verifications', ['plot_id'], unique=False)
    op.create_index(op.f('ix_plot_verifications_survey_id'), 'plot_verifications', ['survey_id'], unique=False)
    op.create_table('preflight_checks',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_preflight_checks_mission_id_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preflight_checks'))
    )
    op.create_index(op.f('ix_preflight_checks_mission_id'), 'preflight_checks', ['mission_id'], unique=False)
    op.create_table('images',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('flight_id', sa.Uuid(), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('alt_m', sa.Float(), nullable=True),
    sa.Column('band_set', sa.String(length=32), nullable=True),
    sa.Column('geotag_source', sa.Enum('exif', 'log', 'manual', name='geotag_source'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name=op.f('fk_images_flight_id_flights'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_images_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_index(op.f('ix_images_survey_id'), 'images', ['survey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_survey_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_preflight_checks_mission_id'), table_name='preflight_checks')
    op.drop_table('preflight_checks')
    op.drop_index(op.f('ix_plot_verifications_survey_id'), table_name='plot_verifications')
    op.drop_index(op.f('ix_plot_verifications_plot_id'), table_name='plot_verifications')
    op.drop_table('plot_verifications')
    op.drop_index(op.f('ix_plot_ai_results_survey_id'), table_name='plot_ai_results')
    op.drop_index(op.f('ix_plot_ai_results_plot_id'), table_name='plot_ai_results')
    op.drop_table('plot_ai_results')
    op.drop_index(op.f('ix_flights_mission_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_damage_assessments_plot_id'), table_name='damage_assessments')
    op.drop_table('damage_assessments')
    op.drop_index(op.f('ix_alerts_survey_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_plot_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_reports_survey_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_rasters_survey_id'), table_name='rasters')
    op.drop_geospatial_index('idx_rasters_bounds', table_name='rasters', postgresql_using='gist', column_name='bounds')
    op.drop_geospatial_table('rasters')
    op.drop_index(op.f('ix_processing_jobs_survey_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_plots_village_id'), table_name='plots')
    op.drop_index(op.f('ix_plots_survey_id'), table_name='plots')
    op.drop_geospatial_index('idx_plots_geom', table_name='plots', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('plots')
    op.drop_index(op.f('ix_missions_survey_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_surveys_village_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_taluka_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_status'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_district_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_created_by'), table_name='surveys')
    op.drop_geospatial_index('idx_surveys_aoi', table_name='surveys', postgresql_using='gist', column_name='aoi')
    op.drop_geospatial_table('surveys')
    op.drop_index(op.f('ix_villages_taluka_id'), table_name='villages')
    op.drop_geospatial_index('idx_villages_geom', table_name='villages', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('villages')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index(op.f('ix_talukas_district_id'), table_name='talukas')
    op.drop_geospatial_index('idx_talukas_geom', table_name='talukas', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('talukas')
    op.drop_geospatial_index('idx_districts_geom', table_name='districts', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('districts')
    # ### end Alembic commands ###
    for enum_name in (
        "user_role",
        "survey_type",
        "survey_status",
        "mission_status",
        "job_kind",
        "job_status",
        "raster_kind",
        "alert_severity",
        "damage_class",
        "health_class",
        "verification_decision",
        "geotag_source",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
