"""real data sources

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 09:05:21.648876
"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TYPE job_kind ADD VALUE IF NOT EXISTS 'satellite'")
    op.execute("ALTER TYPE job_kind ADD VALUE IF NOT EXISTS 'weather'")
    # Phase 2B: synthetic demo records are removed. Deleting a survey cascades to
    # its plots, AI results, rasters, missions and alerts. Demo admin units are
    # replaced by the geoBoundaries import at start-up (references are re-mapped).
    op.execute("DELETE FROM alerts WHERE is_demo")
    op.execute("DELETE FROM surveys WHERE is_demo")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('original_source', sa.String(length=300), nullable=True),
    sa.Column('licence', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('attribution', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('key', name=op.f('uq_datasets_key'))
    )
    op.create_table('weather_daily',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('tmax_c', sa.Float(), nullable=True),
    sa.Column('tmin_c', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_weather_daily_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_daily')),
    sa.UniqueConstraint('survey_id', 'day', name='uq_weather_daily_survey_day')
    )
    op.create_index(op.f('ix_weather_daily_survey_id'), 'weather_daily', ['survey_id'], unique=False)
    op.create_table('satellite_observations',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('plot_id', sa.Uuid(), nullable=True),
    sa.Column('collection', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=True),
    sa.Column('scene_date', sa.Date(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scene_cloud_pct', sa.Float(), nullable=True),
    sa.Column('clear_fraction', sa.Float(), nullable=False),
    sa.Column('valid_pixels', sa.Integer(), nullable=False),
    sa.Column('total_pixels', sa.Integer(), nullable=False),
    sa.Column('ndvi_mean', sa.Float(), nullable=True),
    sa.Column('ndvi_p10', sa.Float(), nullable=True),
    sa.Column('ndvi_p90', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], name=op.f('fk_satellite_observations_plot_id_plots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_satellite_observations_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_satellite_observations'))
    )
    op.create_index(op.f('ix_satellite_observations_plot_id'), 'satellite_observations', ['plot_id'], unique=False)
    op.create_index(op.f('ix_satellite_observations_scene_date'), 'satellite_observations', ['scene_date'], unique=False)
    op.create_index(op.f('ix_satellite_observations_survey_id'), 'satellite_observations', ['survey_id'], unique=False)
    op.create_index('uq_satobs_plot_scene', 'satellite_observations', ['plot_id', 'scene_id'], unique=True, postgresql_where=sa.text('plot_id IS NOT NULL'))
    op.create_index('uq_satobs_survey_scene', 'satellite_observations', ['survey_id', 'scene_id'], unique=True, postgresql_where=sa.text('plot_id IS NULL'))
    op.add_column('districts', sa.Column('source_id', sa.String(length=64), nullable=True))
    op.add_column('districts', sa.Column('dataset_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_districts_dataset_id_datasets'), 'districts', 'datasets', ['dataset_id'], ['id'], ondelete='SET NULL')
    op.add_column('plots', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('plots', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_plots_created_by_users'), 'plots', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('rasters', sa.Column('source', sa.String(length=120), nullable=True))
    op.add_column('rasters', sa.Column('scene_id', sa.String(length=120), nullable=True))
    op.add_column('rasters', sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rasters', sa.Column('cloud_cover', sa.Float(), nullable=True))
    op.add_column('rasters', sa.Column('attribution', sa.String(length=500), nullable=True))
    op.add_column('talukas', sa.Column('source_id', sa.String(length=64), nullable=True))
    op.add_column('talukas', sa.Column('dataset_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_talukas_dataset_id_datasets'), 'talukas', 'datasets', ['dataset_id'], ['id'], ondelete='SET NULL')
    op.add_column('villages', sa.Column('source_id', sa.String(length=64), nullable=True))
    op.add_column('villages', sa.Column('dataset_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_villages_dataset_id_datasets'), 'villages', 'datasets', ['dataset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Enum values added to job_kind and deleted demo rows are not restored.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_villages_dataset_id_datasets'), 'villages', type_='foreignkey')
    op.drop_column('villages', 'dataset_id')
    op.drop_column('villages', 'source_id')
    op.drop_constraint(op.f('fk_talukas_dataset_id_datasets'), 'talukas', type_='foreignkey')
    op.drop_column('talukas', 'dataset_id')
    op.drop_column('talukas', 'source_id')
    op.drop_column('rasters', 'attribution')
    op.drop_column('rasters', 'cloud_cover')
    op.drop_column('rasters', 'acquired_at')
    op.drop_column('rasters', 'scene_id')
    op.drop_column('rasters', 'source')
    op.drop_constraint(op.f('fk_plots_created_by_users'), 'plots', type_='foreignkey')
    op.drop_column('plots', 'created_by')
    op.drop_column('plots', 'source')
    op.drop_constraint(op.f('fk_districts_dataset_id_datasets'), 'districts', type_='foreignkey')
    op.drop_column('districts', 'dataset_id')
    op.drop_column('districts', 'source_id')
    op.drop_index('uq_satobs_survey_scene', table_name='satellite_observations', postgresql_where=sa.text('plot_id IS NULL'))
    op.drop_index('uq_satobs_plot_scene', table_name='satellite_observations', postgresql_where=sa.text('plot_id IS NOT NULL'))
    op.drop_index(op.f('ix_satellite_observations_survey_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_scene_date'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_plot_id'), table_name='satellite_observations')
    op.drop_table('satellite_observations')
    op.drop_index(op.f('ix_weather_daily_survey_id'), table_name='weather_daily')
    op.drop_table('weather_daily')
    op.drop_table('datasets')
    # ### end Alembic commands ###
